services:
  - type: web
    name: app-booking
    env: node
    buildCommand: npm install && npm run install-client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_BYPASS_AUTH
        value: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' https://apis.google.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://*.firebaseio.com https://www.googleapis.com"
      - path: /*
        name: Strict-Transport-Security
        value: "max-age=31536000; includeSubDomains"
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/
      - type: rewrite
        source: /static/*
        destination: /static/
      - type: rewrite
        source: /*
        destination: /index.html
